### ISSUE TITLE
please add support for `/journey`

### ISSUE THREAD

**Issue by mnbf9rca** [ZackaryH8/tfl-api-wrapper#37]
Can you please consider adding support for the [`/journey`](https://api-portal.tfl.gov.uk/api-details#api=Journey&operation=Journey_JourneyResultsByPathFromPathToQueryViaQueryNationalSearchQueryDateQu) API? 

Even basic support using natplanids would be great!

**Comment by ZackaryH8** [comment]
Yep, can do! 👍

**Comment by mnbf9rca** [comment]
amazing - i tried i only know JS not TS :(

**Comment by ZackaryH8** [comment]
Added in 1.7.0

**Comment by mnbf9rca** [comment]
that's super fast - thanks so much!

**Comment by ZackaryH8** [comment]
> that's super fast - thanks so much!

No problem! 😃
